# Site
repository: Oliessem/cv-eu
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Orlando Liessem Filho
title: Civil Engineer / Mechanical Technician
email: orlando@hoengenharia.com.br
# email_title: Email (Email title override)
phone: +55 47 991127742
# phone_title: Phone (Phone title override)
website: https://hoengenharia.com.br
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: oliessem
xing_username: Orlando_LiessemFilho

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  With over twenty years of engineering and design experience, I bring the following qualifications and expertise: Project and team management, including the development and monitoring of processes and key performance indicators such as cost, time and quality; exceptional ability to communicate ideas and knowledge clearly and efficiently, facilitating relationships with internal and external clients; Focus on integration and building interdisciplinary relationships with architects, engineers and technicians; Well-versed in various computer skills such as Office Suite, AutoCAD, Solidworks, Revit and Robot.

 # Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

 # You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
  #  - Lists
  # - Tables
  # - <a href="google.com">Links</a>
  # - Images ![alt text](/images/landscape-trees.jpg "Trees")

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Personal Portfolio
        link: https://ho.hoengenharia.com.br
        link_text: https://ho.hoengenharia.com.br
#       additional_links:
#         - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           icon: fab fa-github
#           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#         - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           icon: fab fa-github
#           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
#       quote: >
#         Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          A large collection of images and designs of my own.
          
  - title: Experience
    layout: list
    content:
      - layout: right
        title: HO Engenharia Ltda
        sub_title: Civil Engineer
        caption: 08/13 - Present
        link: https://hoengenharia.com.br
        quote: >
          Architectural and structural design company
        description: | # this will include new lines to allow paragraphs
          - Design of industrial, commercial and residential structures and installations in reinforced concrete.
          
          - Advice and implementation of BIM for construction companies and companies in the prefabricated components industry.
          
          - Development and standardization of prestressed components.
          
          - Analysis and solution of problems on construction sites.
          
      - layout: right
        title: CSM Equipamentos Ltda
        sub_title: Project Manager
        caption: 01/11 - 01/15
        link: https://www.csmequipamentos.com.br
        # description: | # this will include new lines to allow paragraphs
        #   Construction machinery and equipment design.    
      - layout: right
        title: TAF Plasticos Ltda
        sub_title: Systems Analyst
        caption: 11/09 - 12/10
        link: https://taf.ind.br
        # description: | # this will include new lines to allow paragraphs
        #  Description of role
      - layout: right
        title: Oryzon Máquinas Ltda
        sub_title: Mechanical Technician / Designer
        caption: 02/07 - 09/09
        # link: https://taf.ind.br
        # description: | # this will include new lines to allow paragraphs
        #  Description of role        
      - layout: right
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Bosch Rexroth Ltda
        sub_title: Mechanical Technician / Designer
        caption: 03/02 - 01/07
        link: https://www.bosch.com.br
        # quote: >
        #   Short description of the company (optional)
        # description: | # this will include new lines to allow paragraphs
        #   Description of role        

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: UNISOCIESC
        sub_title: Bachelor's Graduate
        caption: 2009 - 2013
        link: https://www.unisociesc.com.br
        description: | # this will include new lines to allow paragraphs
          Civil Engineer
          
      - layout: top-right
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Escola Técnica Tupy
        sub_title: Technician
        caption: 1995 - 1999
        link: https://www.escolatupy.com.br
        description: | # this will include new lines to allow paragraphs
          Mechanical Technician
          
  - title: More about
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Skills - Softwares
        description: | # this will include new lines to allow paragraphs
          Autodesk Robot / Autodesk Revit / Autodesk AutoCAD / Solidworks / Office / Excel / and more.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Behavior
        description: | # this will include new lines to allow paragraphs
          3D Software Affinity / Ability to Work Under Pressure / Time Management / Adaptability / Buildind Information Modeling (BIM) / Project Management and Coordination / Industrial Engineer Designer / 
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Languages
        description: | # this will include new lines to allow paragraphs
          Portuguese - Mother Tongue / English - Upper Independent / Deutsch - Basic User (A1)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
